import { EntryTypeId } from "@/pages/Entry/enums/EntryTypeId";

export function getDefaultEntryTypesOrder() {
  return [
    EntryTypeId.BreastFeeding,
    EntryTypeId.BottleFeeding,
    EntryTypeId.Burp,
    EntryTypeId.Diaper,
    EntryTypeId.Poop,
    EntryTypeId.Urine,
    EntryTypeId.Sleep,
    EntryTypeId.Walk,
    EntryTypeId.Note,
    EntryTypeId.Play,
    EntryTypeId.Cry,
    EntryTypeId.Regurgitation,
    EntryTypeId.Vomit,
    EntryTypeId.Fart,
    EntryTypeId.MilkExtraction,
    EntryTypeId.CarRide,
    EntryTypeId.Hiccups,
    EntryTypeId.Weight,
    EntryTypeId.Size,
    EntryTypeId.HeadCircumference,
    EntryTypeId.Bath,
    EntryTypeId.NasalHygiene,
    EntryTypeId.NailCutting,
    EntryTypeId.Temperature,
    EntryTypeId.Teeth,
    EntryTypeId.Symptom,
    EntryTypeId.Medicine,
    EntryTypeId.MedicalFollowUp,
    EntryTypeId.Hospital,
    EntryTypeId.Vaccine,
    EntryTypeId.SolidFood,
    EntryTypeId.BabyMash,
    EntryTypeId.VitaminsAndSupplements,
    EntryTypeId.AwakeTime,
    EntryTypeId.Activity,
    EntryTypeId.BabyCare,
    EntryTypeId.BabyToilet,
    EntryTypeId.BellyTime,
  ];
}
